[DNM] Squash AppOps 2/3
commit 5e160232bd8ded2d031db9396ea5de93fa80f039
Author: riddle_hsu <riddle_hsu@htc.com>
Date:   Tue Apr 12 11:35:35 2016 +0800

    Fix race condition when writing UidState of appops.

    Without synchronized this, mUidStates may still be changed,
    e.g. uidState.opModes may be set to null then result NPE.

    Make a copy in synchronized to write as allOps.

    Change-Id: Id5d0e587d7eb6aefd008d522a80a643e1c326019

commit 897330f640a9077df5ddc0f088ae06f9f5a36ba4
Author: c_jyuan <yuanjiao@codeaurora.org>
Date:   Tue Jun 14 14:43:38 2016 +0800

    AppOpsManager: Fix wrong coarse location permission issue

    Android intentionally defines 3 duplicated coarse location permissions in
    the mapping table, but for CTA security, it does not allow one switch to
    control the other 2. Therefore, it need to update the table with exact permissions.
    However, it is not proper to mainline currently to conflict AOSP's way.

    Change-Id: If534a21beb32253abb4f603c7f36b5a8b0ab0601

commit 9192b1ed8213a69d0d89ba9a3abd303cb41aa4d1
Author: riddle_hsu <riddle_hsu@htc.com>
Date:   Fri Apr 15 12:05:06 2016 +0800

    AppOps: Fix NPE from AppOpsManager.checkPackage.

    Since commit 0fcef84, any application can use below code
    to insert an invalid op record:
        appOpsManager.checkPackage(0, null);

    Use below command will see the invalid record breaks writeState.
      adb shell dumpsys appops write-settings

      Exception occurred while dumping:
      java.lang.NullPointerException: Attempt to invoke virtual method
      'boolean java.lang.String.equals(java.lang.Object)'
      on a null object reference
            at com.android.server.AppOpsService.writeState

    And system server will crash in 30 minutes when saving the xml.

    Change-Id: I6ebd24126f03bda048cc4070d24783887e4164f9

commit 93c763267aca99773b213d45b2bfc3418861e368
Author: Sam Mortimer <sam@mortimer.me.uk>
Date:   Wed Nov 13 21:30:08 2013 -0800

    AppOps: Enable MODE_IGNORED for OP_WAKE_LOCK

    *) Kitkat commit log highlights that the current
       implementation state is for auditing only
       https://android.googlesource.com/platform/frameworks/base/+/713df150b92a0a5eea877f99405e31eefbf93a09

    *) We go one step further and honour MODE_IGNORED
       for OP_WAKE_LOCK.

    Change-Id: I889227ca24a508a0d96bd43594c5179ba758ae3d

commit 29e068279ab641d4f0810d9b990f09c39f10854f
Author: George G <kreach3r@users.noreply.github.com>
Date:   Sun Dec 25 02:22:50 2016 +0200

    AppOps: Avoid RuntimeException and log spam

    We know Google Play Services have free reign and do whatever they want with the other Google apps.

    This commit stops this logspam:

    12-25 02:14:01.740   878 31531 W AppOps  : Bad call: specified package com.google.android.gms under uid 10061 but it is really 10021
    12-25 02:14:01.740   878 31531 W AppOps  : java.lang.RuntimeException: here
    12-25 02:14:01.740   878 31531 W AppOps  :      at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1257)
    12-25 02:14:01.740   878 31531 W AppOps  :      at com.android.server.AppOpsService.checkPackage(AppOpsService.java:976)
    12-25 02:14:01.740   878 31531 W AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)
    12-25 02:14:01.740   878 31531 W AppOps  :      at android.os.Binder.execTransact(Binder.java:565)

    It also fixes this awful log output. ("here"? really?)

    In my case, the 10061 app was Google Keep.

    Change-Id: Iffad7d4925fb140ec04e8a89447927ade7310595

commit 1d28ce782a5db837f91e49464456f9b31f52c7dc
Author: Shashank Mittal <mittals@codeaurora.org>
Date:   Thu Sep 21 19:44:51 2017 +0800

    AppOps: Add BOOT_COMPLETED operation
    Add BOOT_COMPLETED operation in AppOps.

    This operation is used to allow user to control auto start of
    applications and services at bootup.

    @xyyx: adapt to O

    Change-Id: Ia00bfafe5f283779f1cc51b2460b92a914d9f4e0

Change-Id: I6c40101e75a91d2fd03a86436014c618afd9e231